name: CMake

on: [push, pull_request, repository_dispatch, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare (ubuntu)
      run: |
           sudo apt-get update
           sudo apt-get install -y gcc-11 g++-11
           sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Configure (ubuntu)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON
      env:
        CC:   gcc-11
        CXX:  g++-11
      if: matrix.os == 'ubuntu-latest'

    - name: Configure (windows)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON
      if: matrix.os == 'windows-latest'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build

    - name: Install
      run: |
           mkdir install
           cmake --install ${{github.workspace}}/build --strip

    - name: Pack
      run: |
           cd ${{github.workspace}}/build
           cpack -C ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}/build/packages/