name: CMake

on: [push, pull_request, repository_dispatch, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86, x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare (ubuntu)
      run: |
           sudo apt-get update
           sudo apt-get install -y gcc-11 g++-11
           sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Configure (ubuntu / x86)
      run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y gcc-11-multilib lib32stdc++-11-dev libc6:i386 libx11-dev:i386
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_{C,CXX}_FLAGS=-m32
      env:
        CC:   gcc-11
        CXX:  g++-11
      if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86'

    - name: Configure (ubuntu / x64)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON
      env:
        CC:   gcc-11
        CXX:  g++-11
      if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'

    - name: Configure (windows / x86)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON -T host=x86 -A win32
      if: matrix.os == 'windows-latest' && matrix.arch == 'x86'

    - name: Configure (windows / x64)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON
      if: matrix.os == 'windows-latest' && matrix.arch == 'x64'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build

    - name: Install
      run: |
           mkdir install
           cmake --install ${{github.workspace}}/build --strip

    - name: Pack
      run: |
           cd ${{github.workspace}}/build
           cpack -C ${{env.BUILD_TYPE}}