name: docs

on:
  workflow_run:
    workflows: [CMake]
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@1.9.4
      with:
        doxyfile-path: ./docs/doxygen.conf
        working-directory: '.'
        enable-latex: true

    - name: Install Doxybook2
      uses: engineerd/configurator@v0.0.8
      with:
        name: doxybook2
        pathInArchive: bin/doxybook2
        fromGitHubReleases: true
        repo: matusnovak/doxybook2
        version: latest
        urlTemplate: https://github.com/matusnovak/doxybook2/releases/download/{{version}}/doxybook2-linux-amd64-{{version}}.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Doxybook2
      shell: bash
      run: |
        doxybook2 --version
        cd ${{github.workspace}}/docs
        mkdir _doxybook
        doxybook2 --input _doxygen/xml --output _doxybook --config config.json

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}/docs/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DOCS_TOKEN }}
        external_repository: liblava/liblava.github.io
        publish_dir: ${{github.workspace}}/docs/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        user_name: thelavablock
        user_email: the@lava-block.com
        publish_branch: main
      if: ${{ github.repository_owner == 'liblava' }}
